<?xml version='1.0' encoding='UTF-8'?> 
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version='1.0'>
  <dict>
    <key>name</key>
    <string>i3-wm Config</string>
    <key>author</key>
    <string>skk</string>
    <key>scopeName</key>
    <string>source.i3wm_config</string>
    <key>fileTypes</key>
    <array>
      <string>i3/config</string>
      <string>config</string>
    </array>
    <key>uuid</key>
    <string>bb9ebd33-1b88-4310-acef-41720bcac38f</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>((#).*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>comment.source.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>set</string>
        <key>match</key>
        <string>(set)\s*(\$\w*)\s*(\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.scope.variable.other.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>ipc_socket</string>
        <key>match</key>
        <string>(ipc-socket)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>reload</string>
        <key>match</key>
        <string>(reload)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>restart</string>
        <key>match</key>
        <string>(restart)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>layout</string>
        <key>match</key>
        <string>(layout)\s*(default|tabbed|stacking|split v|split h)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>layout_toggle</string>
        <key>match</key>
        <string>(layout toggle)\s*(split|all)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>split</string>
        <key>match</key>
        <string>(split)\s*(vertical|horizontal|v|h)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>rename_workspace</string>
        <key>match</key>
        <string>(rename workspace)\s*(\w*)\s*(to)\s*(\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>workspace</string>
        <key>match</key>
        <string>(workspace)\s*(next|prev|next_on_output|prev_on_output|back_and_forth|(?:\w)*|(?:\d*\s*\w*))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move__container_or_workspace</string>
        <key>match</key>
        <string>(move)\s*(workspace|container)\s*(to)\s*(output)\s*(left|right|down|up|[\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move_workspace</string>
        <key>match</key>
        <string>(move)\s*(workspace)\s*(next|prev|next_on_output|prev_on_output|back_and_forth|(?:\w)*|(?:\d*\s*\w*))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move__window_or_container</string>
        <key>match</key>
        <string>(move)\s*(window|container)\s*(to)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move_scratchpad</string>
        <key>match</key>
        <string>(move)\s*(scratchpad)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>scratchpad_show</string>
        <key>match</key>
        <string>(scratchpad)\s*(show)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bar</string>
        <key>match</key>
        <string>(?:^ *|\G *)(bar)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>position</string>
        <key>match</key>
        <string>(position)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>status_command</string>
        <key>match</key>
        <string>(status_command)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>tray_output</string>
        <key>match</key>
        <string>(tray_output)\s*(\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>background</string>
        <key>match</key>
        <string>(background)\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>focused_workspace</string>
        <key>match</key>
        <string>(focused_workspace)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>active_workspace</string>
        <key>match</key>
        <string>(active_workspace)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>inactive_workspace</string>
        <key>match</key>
        <string>(inactive_workspace)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>statusline</string>
        <key>match</key>
        <string>(statusline)\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>exec</string>
        <key>match</key>
        <string>(exec)\s*(\-\-no-startup-id)?\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>font_pango</string>
        <key>match</key>
        <string>(font\ pango\:)\s*([ \w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>font</string>
        <key>match</key>
        <string>(font)\s*([-\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>force_xinerama</string>
        <key>match</key>
        <string>(force_xinerama)\s*(no|yes)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>floating_modifier</string>
        <key>match</key>
        <string>(floating_modifier)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.scope.variable.other.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_focused</string>
        <key>match</key>
        <string>(client.focused)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_focused_inactive</string>
        <key>match</key>
        <string>(client\.focused\_inactive)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_unfocused</string>
        <key>match</key>
        <string>(client\.unfocused)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.string.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>colors</string>
        <key>match</key>
        <string>(colors)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.scope.block.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bindcode</string>
        <key>match</key>
        <string>(bindcode)\s*(--release)?\s*(\d*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3wm_config</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bindsym</string>
        <key>match</key>
        <string>(bindsym)\s*(--release)?\s*([$\w\+]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.i3wm_config</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3wm_config</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.scope.variable.other.i3wm_config</string>
          </dict>
        </dict>
      </dict>
    </array>
  </dict>
</plist>
