<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>i3/config</string>
		<string>config</string>
	</array>
	<key>name</key>
	<string>i3-wm Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.source.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)((#).*)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(set)\s*(.*)</string>
			<key>name</key>
			<string>set</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(ipc-socket)\s*(.*)</string>
			<key>name</key>
			<string>ipc_socket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(position)\s*(.*)</string>
			<key>name</key>
			<string>position</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(status_command)\s*(.*)</string>
			<key>name</key>
			<string>status_command</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(tray_output)\s*(.*)</string>
			<key>name</key>
			<string>tray_output</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(background)\s*(.*)</string>
			<key>name</key>
			<string>background</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(focused_workspace)\s*(.*)</string>
			<key>name</key>
			<string>focused_workspace</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(active_workspace)\s*(.*)</string>
			<key>name</key>
			<string>active_workspace</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(inactive_workspace)\s*(.*)</string>
			<key>name</key>
			<string>inactive_workspace</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(statusline)\s*(.*)</string>
			<key>name</key>
			<string>statusline</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(exec)\s*(.*)</string>
			<key>name</key>
			<string>exec</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(font\ pango\:)\s*([ \w]*)</string>
			<key>name</key>
			<string>font_pango</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(bindsym|bindcode)\s*(.*)\s*(.*)</string>
			<key>name</key>
			<string>bind</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(font)\s*([-\w]*)</string>
			<key>name</key>
			<string>font</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(force_xinerama)\s*(.*)</string>
			<key>name</key>
			<string>force_xinerama</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(floating_modifier)\s*(.*)</string>
			<key>name</key>
			<string>floating_modifier</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(client\.focused)\s*(.*)\s*(.*)\s*(.*)\s*(.*)</string>
			<key>name</key>
			<string>client_focused</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(client\.focused_inactive)\s*(.*)\s*(.*)\s*(.*)\s*(.*)</string>
			<key>name</key>
			<string>client_focused_inactive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(client\.unfocused)\s*(.*)\s*(.*)\s*(.*)\s*(.*)</string>
			<key>name</key>
			<string>client_unfocused</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(bar)\s*(.*)</string>
			<key>name</key>
			<string>bar</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.i3wm_config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.i3wm_config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)(colors)\s*(.*)</string>
			<key>name</key>
			<string>colors</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.i3wm_config</string>
	<key>uuid</key>
	<string>bb9ebd33-1b88-4310-acef-41720bcac38f</string>
</dict>
</plist>
